# Generated by Django 4.1.2 on 2022-12-24 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, verbose_name="Имя актива")),
                (
                    "ticker",
                    models.CharField(max_length=64, verbose_name="ticker актива"),
                ),
                ("figi", models.CharField(max_length=32, verbose_name="FIGI")),
                ("type", models.CharField(max_length=32, verbose_name="Тип актива")),
                ("currency", models.CharField(max_length=16, verbose_name="валюта")),
                (
                    "first_candle_date",
                    models.DateTimeField(verbose_name="дата начала истории продаж"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Название портфеля"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Стоимость портфеля",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAsset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_buy", models.DateField(verbose_name="дата операции")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Сумма сделки"
                    ),
                ),
                (
                    "count",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Количество"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoryPriceAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="дата операции")),
                (
                    "closed",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="цена закрытия"
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="цена открытия"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="минимальная цена за день",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="максимальная цена за день",
                    ),
                ),
                ("volume", models.IntegerField(verbose_name="объем торгов")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.asset",
                    ),
                ),
            ],
        ),
    ]
