# Generated by Django 4.1.2 on 2022-12-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="currency",
            field=models.CharField(max_length=16, verbose_name="валюта"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="figi",
            field=models.CharField(max_length=32, verbose_name="FIGI"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Имя актива"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="ticker",
            field=models.CharField(max_length=64, verbose_name="ticker актива"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(max_length=32, verbose_name="Тип актива"),
        ),
    ]
