# Generated by Django 4.2 on 2023-05-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_category_name'),
        ('mainapp', '0002_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
    ]
