# Generated by Django 4.1.2 on 2023-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_limitinmonth_month_alter_limitstartmonth_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='amount_buy',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сколько купил'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='amount_sell',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сколько продал'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='price_basic_currency',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сколько вышло в стандартной валюте'),
        ),
        migrations.AlterField(
            model_name='moneysum',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма валюты у пользователя'),
        ),
        migrations.AlterField(
            model_name='moneysum',
            name='conversion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Конверсия к стандартной валюте пользователя'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price_basic_currency',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сколько вышло в стандартной валюте'),
        ),
    ]
