# Generated by Django 4.1.2 on 2023-10-08 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_conversion_amount_buy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=64, verbose_name='Название инвестиции')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма вложения')),
                ('price_now', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текщая стоимость')),
                ('conversion_price_now', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Конверсия к стандартной валюте текущей стоимости')),
                ('conversion_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Конверсия к стандартной валюте вложений')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPriceInvestment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма вложения')),
                ('price_now', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текщая стоимость')),
                ('conversion_price_now', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Конверсия к стандартной валюте текущей стоимости')),
                ('conversion_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Конверсия к стандартной валюте вложений')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.currency')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.investment')),
            ],
        ),
    ]
