# Generated by Django 4.1.2 on 2023-10-11 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_historymoneyallsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymoneyallsum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
