# Generated by Django 4.1.2 on 2023-10-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_historymoneyallsum_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymoneyallsum',
            name='created_at',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
